version: '2'

# database ports are mapped to the host for debug purposes

services:
  redis:
    command: --save "" --appendonly no
    image: redis:alpine
    ports:
      - "6379:6379"

  db:
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"

  bot:
    extends:
      file: docker-compose-shared.yml
      service: bot
    build: .
    depends_on:
      - db
      - redis
    environment:
      - ENV=development
    ports:
      - "80:80"
    volumes:
      - ./lua:/srv/app/lua
      - ./conf:/srv/app/conf
      - ./i18n:/srv/app/i18n
