version: '3'

# database ports are mapped to the host for debug purposes

services:
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"

  bot:
    build: .
    depends_on:
      - db
    environment:
      - TG_TOKEN
      - SUPERADMINS
      - LOG
      - CHANNEL
      - SOURCE
      - GROUP
      - CORE_LANG
    restart: always
    volumes:
      - ./:/srv/app
