version: '3'

# database ports are mapped to the host for debug purposes

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  db:
    image: postgres:alpine
    ports:
      - "5432:5432"

  bot:
    build: .
    depends_on:
      - db
      - redis
    environment:
      - TG_TOKEN
    volumes:
      - ./:/srv/app
